# Generated by Django 5.2.4 on 2025-08-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=0, help_text='Duration in minutes for duration alerts', null=True),
        ),
    ]
