# Generated by Django 5.2.4 on 2025-08-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
